{
  "uid" : "34036144644cbdca",
  "name" : "User can't successfully log in with invalid password.",
  "fullName" : "tests.core_features.test_login.TestLogin#test_login_with_invalid_password",
  "historyId" : "0ca18d8bd97e96e2fad3ec13e04117a8",
  "time" : {
    "start" : 1704908682724,
    "stop" : 1704908682724,
    "duration" : 0
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL reason: Health check failed with status code 502\n\n_pytest.outcomes.XFailed: Health check failed with status code 502",
  "statusTrace" : "conftest.py:32: in health_check\n    pytest.xfail(reason=f\"Health check failed with status code {response.status_code}\")\nE   _pytest.outcomes.XFailed: Health check failed with status code 502\n        response   = <Response [502]>\n        url        = 'https://parabank.parasoft.com/parabank'",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "Health check request",
    "time" : {
      "start" : 1704908682351,
      "stop" : 1704908682639,
      "duration" : 288
    },
    "status" : "failed",
    "statusMessage" : "_pytest.outcomes.XFailed: Health check failed with status code 502\n",
    "statusTrace" : "  File \"/usr/local/lib/python3.11/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1123, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/fixtures.py\", line 902, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/workspace/conftest.py\", line 32, in health_check\n    pytest.xfail(reason=f\"Health check failed with status code {response.status_code}\")\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/outcomes.py\", line 256, in xfail\n    raise XFailed(reason)\n",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "stepsCount" : 0,
    "hasContent" : true
  }, {
    "name" : "_session_faker",
    "time" : {
      "start" : 1704908682330,
      "stop" : 1704908682350,
      "duration" : 20
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "feature",
    "value" : "PARA-15261: User login"
  }, {
    "name" : "epic",
    "value" : "PARA-15240: User registration and authentication"
  }, {
    "name" : "severity",
    "value" : "Minor"
  }, {
    "name" : "parentSuite",
    "value" : "tests.core_features"
  }, {
    "name" : "suite",
    "value" : "test_login"
  }, {
    "name" : "subSuite",
    "value" : "TestLogin"
  }, {
    "name" : "host",
    "value" : "457bd63967c0"
  }, {
    "name" : "thread",
    "value" : "1-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.core_features.test_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "minor",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 0,
        "skipped" : 6,
        "passed" : 0,
        "unknown" : 0,
        "total" : 6
      },
      "items" : [ {
        "uid" : "bf6294b63c28caed",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704874970180,
          "stop" : 1704874971491,
          "duration" : 1311
        }
      }, {
        "uid" : "d87ec95d2bd7a1d7",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704839544422,
          "stop" : 1704839545491,
          "duration" : 1069
        }
      }, {
        "uid" : "ceab7a397b75762c",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704789358098,
          "stop" : 1704789359199,
          "duration" : 1101
        }
      }, {
        "uid" : "bb142fe10b5e53ec",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704759028518,
          "stop" : 1704759029330,
          "duration" : 812
        }
      }, {
        "uid" : "cce9cde06874d2bf",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Known server-side issue\n\n_pytest.outcomes.XFailed: Known server-side issue",
        "time" : {
          "start" : 1704756568705,
          "stop" : 1704756570047,
          "duration" : 1342
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "34036144644cbdca.json",
  "parameterValues" : [ ]
}