{
  "uid" : "aa38cce94a05a879",
  "name" : "User can't transfer funds leaving amount field empty",
  "fullName" : "tests.core_features.test_funds_transfer.TestFundsTransfer#test_funds_transfer_with_empty_amount",
  "historyId" : "5d72f60001d4c80e4581c8fae63d198e",
  "time" : {
    "start" : 1705016475540,
    "stop" : 1705016477396,
    "duration" : 1856
  },
  "status" : "skipped",
  "statusMessage" : "XFAIL reason: Execution blocked by Cloudflare\n\n_pytest.outcomes.XFailed: Execution blocked by Cloudflare",
  "statusTrace" : "tests/core_features/test_funds_transfer.py:106: in test_funds_transfer_with_empty_amount\n    block_checker(driver)\n        driver     = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"e8f22867e6e6d0f53bac75cdc7486354\")>\n        new_user   = NewUser(first_name='Virginia', last_name='White', address='597 Emily Summit\\nWest Phillip, AR 10042', city='Christinem..._number='453.215.5763x700', ssn='689-91-0721', username='rebecca81', password='PbC06CTo(w', email='sscott@example.net')\n        register_page = <src.pages.register_page.RegisterPage object at 0x7fa4fdebecd0>\n        self       = <test_funds_transfer.TestFundsTransfer object at 0x7fa501031a10>\nsrc/utils/block_checker.py:8: in block_checker\n    pytest.xfail(reason=\"Execution blocked by Cloudflare\")\nE   _pytest.outcomes.XFailed: Execution blocked by Cloudflare\n        driver     = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"e8f22867e6e6d0f53bac75cdc7486354\")>",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_session_faker",
    "time" : {
      "start" : 1705016395533,
      "stop" : 1705016395554,
      "duration" : 21
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "Initialize driver",
    "time" : {
      "start" : 1705016474698,
      "stop" : 1705016475539,
      "duration" : 841
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  }, {
    "name" : "Health check request",
    "time" : {
      "start" : 1705016395554,
      "stop" : 1705016396123,
      "duration" : 569
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 0,
    "hasContent" : false
  } ],
  "testStage" : {
    "status" : "skipped",
    "statusMessage" : "XFAIL reason: Execution blocked by Cloudflare\n\n_pytest.outcomes.XFailed: Execution blocked by Cloudflare",
    "statusTrace" : "tests/core_features/test_funds_transfer.py:106: in test_funds_transfer_with_empty_amount\n    block_checker(driver)\n        driver     = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"e8f22867e6e6d0f53bac75cdc7486354\")>\n        new_user   = NewUser(first_name='Virginia', last_name='White', address='597 Emily Summit\\nWest Phillip, AR 10042', city='Christinem..._number='453.215.5763x700', ssn='689-91-0721', username='rebecca81', password='PbC06CTo(w', email='sscott@example.net')\n        register_page = <src.pages.register_page.RegisterPage object at 0x7fa4fdebecd0>\n        self       = <test_funds_transfer.TestFundsTransfer object at 0x7fa501031a10>\nsrc/utils/block_checker.py:8: in block_checker\n    pytest.xfail(reason=\"Execution blocked by Cloudflare\")\nE   _pytest.outcomes.XFailed: Execution blocked by Cloudflare\n        driver     = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"e8f22867e6e6d0f53bac75cdc7486354\")>",
    "steps" : [ {
      "name" : "Navigate to Register page",
      "time" : {
        "start" : 1705016475540,
        "stop" : 1705016476202,
        "duration" : 662
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    }, {
      "name" : "Register a new user",
      "time" : {
        "start" : 1705016476202,
        "stop" : 1705016477395,
        "duration" : 1193
      },
      "status" : "failed",
      "statusMessage" : "_pytest.outcomes.XFailed: Execution blocked by Cloudflare\n",
      "statusTrace" : "  File \"/usr/workspace/tests/core_features/test_funds_transfer.py\", line 106, in test_funds_transfer_with_empty_amount\n    block_checker(driver)\n  File \"/usr/workspace/src/utils/block_checker.py\", line 8, in block_checker\n    pytest.xfail(reason=\"Execution blocked by Cloudflare\")\n  File \"/usr/local/lib/python3.11/site-packages/_pytest/outcomes.py\", line 256, in xfail\n    raise XFailed(reason)\n",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : true,
      "stepsCount" : 0,
      "hasContent" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : true,
    "stepsCount" : 2,
    "hasContent" : true
  },
  "afterStages" : [ {
    "name" : "Initialize driver::0",
    "time" : {
      "start" : 1705016477400,
      "stop" : 1705016477456,
      "duration" : 56
    },
    "status" : "passed",
    "steps" : [ {
      "name" : "Terminate driver",
      "time" : {
        "start" : 1705016477400,
        "stop" : 1705016477456,
        "duration" : 56
      },
      "status" : "passed",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "stepsCount" : 0,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false,
    "stepsCount" : 1,
    "hasContent" : true
  } ],
  "labels" : [ {
    "name" : "severity",
    "value" : "Minor"
  }, {
    "name" : "feature",
    "value" : "PARA-15270: Funds transfer"
  }, {
    "name" : "epic",
    "value" : "PARA-15242: Funds operations"
  }, {
    "name" : "parentSuite",
    "value" : "tests.core_features"
  }, {
    "name" : "suite",
    "value" : "test_funds_transfer"
  }, {
    "name" : "subSuite",
    "value" : "TestFundsTransfer"
  }, {
    "name" : "host",
    "value" : "c18f53ecc522"
  }, {
    "name" : "thread",
    "value" : "1-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "tests.core_features.test_funds_transfer"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "minor",
    "retries" : [ ],
    "categories" : [ ],
    "history" : {
      "statistic" : {
        "failed" : 0,
        "broken" : 1,
        "skipped" : 2,
        "passed" : 5,
        "unknown" : 0,
        "total" : 8
      },
      "items" : [ {
        "uid" : "1c103e82e2643cb7",
        "status" : "passed",
        "time" : {
          "start" : 1704912999971,
          "stop" : 1704913004539,
          "duration" : 4568
        }
      }, {
        "uid" : "38cf0b32c6a7a8e1",
        "status" : "skipped",
        "statusDetails" : "XFAIL reason: Health check failed with status code 502\n\n_pytest.outcomes.XFailed: Health check failed with status code 502",
        "time" : {
          "start" : 1704908682718,
          "stop" : 1704908682718,
          "duration" : 0
        }
      }, {
        "uid" : "2be7a4e3452ef000",
        "status" : "passed",
        "time" : {
          "start" : 1704874961761,
          "stop" : 1704874967148,
          "duration" : 5387
        }
      }, {
        "uid" : "22c7579b3adc13f0",
        "status" : "passed",
        "time" : {
          "start" : 1704839519492,
          "stop" : 1704839541356,
          "duration" : 21864
        }
      }, {
        "uid" : "8d53e8b31d6fe83f",
        "status" : "broken",
        "statusDetails" : "selenium.common.exceptions.StaleElementReferenceException: Message: stale element reference: stale element not found\n  (Session info: headless chrome=119.0.6045.159); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception",
        "time" : {
          "start" : 1704789353115,
          "stop" : 1704789355175,
          "duration" : 2060
        }
      }, {
        "uid" : "90268d5bbc49fc93",
        "status" : "passed",
        "time" : {
          "start" : 1704759021274,
          "stop" : 1704759025947,
          "duration" : 4673
        }
      }, {
        "uid" : "117c3fb2cbcbf3db",
        "status" : "passed",
        "time" : {
          "start" : 1704756560139,
          "stop" : 1704756565432,
          "duration" : 5293
        }
      } ]
    },
    "tags" : [ ]
  },
  "source" : "aa38cce94a05a879.json",
  "parameterValues" : [ ]
}